[package]
name = "example"
version = "0.1.0"
authors = ["Fran√ßois Mockers <mockersf@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_dynamodb = { git = "https://github.com/mockersf/serde_dynamodb" }
serde_dynamodb_derive = { git = "https://github.com/mockersf/serde_dynamodb" }

rusoto_core = "0.33"
rusoto_dynamodb = "0.33"

uuid = { version = "0.6", features = ["serde", "v4"] }
