[package]
name = "serde_dynamodb"
version = "0.1.1"
authors = ["Fran√ßois Mockers <mockersf@gmail.com>"]
description = "de/serialize struct to HashMap<String, AttributeValue> with Serde to use with Rusoto DynamoDB"
repository = "https://github.com/mockersf/serde_dynamodb"
homepage = "https://github.com/mockersf/serde_dynamodb"
documentation = "https://docs.rs/serde_dynamodb"
keywords = ["serde", "dynamodb", "rusoto"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "mockersf/serde_dynamodb" }

[dependencies]
serde = "1.0.32"
rusoto_dynamodb = "0.32"

[dev-dependencies]
serde_derive = "1.0.32"
rusoto_core = "0.32"
rusoto_dynamodb = "0.32"
